version: '3.9'

services:
  popcorn-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: popcorn-web:latest
    container_name: popcorn-web
    env_file:
      .env
    ports:
      - "8081:8081"
    networks:
      - popcorn-network
    restart: always
    command: nginx -g 'daemon off;'

networks:
  popcorn-network:
    name: popcorn-network
    external: true